INSERT INTO WATER VALUES (0, 'Spring', 200);
INSERT INTO WATER VALUES (1, 'Sparkling', 300);
INSERT INTO WATER VALUES (2, 'Distilled', 400);

INSERT INTO USER VALUES (0, 'Владислав', 'Цай', 'admin', 'admin', 'ADMIN', '0');
INSERT INTO USER VALUES (1, 'Даня', 'Шеповалов', 'user', 'qwerty', 'CLIENT', '10000');

INSERT INTO BOTTLE_SIZE VALUES (0, 0.5);
INSERT INTO BOTTLE_SIZE VALUES (1, 1);
INSERT INTO BOTTLE_SIZE VALUES (2, 1.5);
INSERT INTO BOTTLE_SIZE VALUES (3, 5);
INSERT INTO BOTTLE_SIZE VALUES (4, 19);

