INSERT INTO WATER VALUES (0, 'Spring', 200);
INSERT INTO WATER VALUES (1, 'Sparkling', 300);
INSERT INTO WATER VALUES (2, 'Distilled', 400);

INSERT INTO USER VALUES (0, 'Владислав', 'Цай', 'm047wbm@mail.ru', '123', 'ADMIN', '0.0', 'ENABLED');

INSERT INTO BOTTLE_SIZE VALUES (0, 0.5);
INSERT INTO BOTTLE_SIZE VALUES (1, 1);
INSERT INTO BOTTLE_SIZE VALUES (2, 1.5);
INSERT INTO BOTTLE_SIZE VALUES (3, 5);
INSERT INTO BOTTLE_SIZE VALUES (4, 19);

