CREATE TABLE WATER (ID INT PRIMARY KEY AUTO_INCREMENT, TYPE VARCHAR(255), PRICE_PER_LITER INT);

CREATE TABLE USER (ID INT PRIMARY KEY AUTO_INCREMENT, FIRSTNAME VARCHAR(255), LASTNAME  VARCHAR(255), LOGINEMAIL  VARCHAR(255), PASSWORD  VARCHAR(255), ROLE VARCHAR(10), WALLET DOUBLE, STATE VARCHAR(10));

CREATE TABLE CUSTOMER_ADDRESS(ID INT PRIMARY KEY AUTO_INCREMENT, CITY VARCHAR(255), STREET VARCHAR(255), HOUSE_NUMBER VARCHAR (255), APARTMENT_NUMBER VARCHAR(255), PHONE_NUMBER VARCHAR (255), CUSTOMER_ID INT);
ALTER TABLE CUSTOMER_ADDRESS ADD FOREIGN KEY (CUSTOMER_ID) REFERENCES USER(ID);

CREATE TABLE BOTTLE_SIZE (ID INT PRIMARY KEY AUTO_INCREMENT, SIZE DOUBLE);

CREATE TABLE ORDER_CONTENT (ID INT PRIMARY KEY AUTO_INCREMENT, WATER_ID INT, BOTTLE_SIZE_ID INT, QUANTITY INT, CUSTOMER_ORDER_ID INT);
ALTER TABLE ORDER_CONTENT ADD FOREIGN KEY (WATER_ID) REFERENCES WATER(ID);
ALTER TABLE ORDER_CONTENT ADD FOREIGN KEY (BOTTLE_SIZE_ID) REFERENCES BOTTLE_SIZE(ID);
ALTER TABLE ORDER_CONTENT ADD FOREIGN KEY (CUSTOMER_ORDER_ID) REFERENCES CUSTOMER_ORDER(ID);

CREATE TABLE CUSTOMER_ORDER (ID INT PRIMARY KEY AUTO_INCREMENT, CUSTOMER_ID INT, AMOUNT DOUBLE, ORDER_DATE DATE, STATUS VARCHAR(20));
ALTER TABLE CUSTOMER_ORDER ADD FOREIGN KEY (CUSTOMER_ID) REFERENCES USER(ID);