CREATE TABLE WATER_TYPE (ID INT PRIMARY KEY AUTO_INCREMENT, TYPE VARCHAR(255));

CREATE TABLE WATER (ID INT PRIMARY KEY AUTO_INCREMENT, WATER_TYPE_ID INT, PRICEPERLITRE INT);
ALTER TABLE WATER ADD FOREIGN KEY (WATER_TYPE_ID) REFERENCES WATER_TYPE(ID);

CREATE TABLE USER (ID INT PRIMARY KEY AUTO_INCREMENT, FIRSTNAME VARCHAR(255), LASTNAME  VARCHAR(255), LOGINEMAIL  VARCHAR(255), PASSWORD  VARCHAR(255), ROLE VARCHAR(10), WALLET INT);

CREATE TABLE BOTTLE_SIZE (ID INT PRIMARY KEY AUTO_INCREMENT, SIZE DOUBLE);

CREATE TABLE ORDER_CONTENT (ID INT PRIMARY KEY AUTO_INCREMENT, WATER_TYPE_ID INT, BOTTLE_SIZE_ID INT, QUANTITY INT);
ALTER TABLE ORDER_CONTENT ADD FOREIGN KEY (BOTTLE_SIZE_ID) REFERENCES BOTTLE_SIZE(ID);
ALTER TABLE ORDER_CONTENT ADD FOREIGN KEY (WATER_TYPE_ID) REFERENCES WATER_TYPE(ID);

CREATE TABLE CUSTOMER_CART (ID INT PRIMARY KEY AUTO_INCREMENT, CUSTOMER_ID INT, ORDER_CONTENT_ID INT, AMOUNT INT);
ALTER TABLE CUSTOMER_CART ADD FOREIGN KEY (CUSTOMER_ID) REFERENCES USER(ID);
ALTER TABLE CUSTOMER_CART ADD FOREIGN KEY (ORDER_CONTENT_ID) REFERENCES ORDER_CONTENT(ID);





